version: "3.8"

services:
  rmq:
    image: library/rabbitmq:management-alpine
    ports:
    - 15672:15672
    - 5672:5672

  redis:
    image: redis
    ports:
    - 6379:6379

  streammit:
    build:
      context: ./streammit
      dockerfile: Dockerfile
    env_file:
      - .env
    #environment:
      #REDDIT_CLIENT_ID:
      #REDDIT_CLIENT_SECRET:
      #REDDIT_USER_AGENT:
      #SUBREDDIT:
      #RMQ_HOST:

  parssit:
    build:
      context: ./parssit
      dockerfile: Dockerfile
    env_file:
      - .env
    #environment:
      #SUBREDDIT:
      #RMQ_HOST:
      #REDIS_HOST:

  storrit:
    build:
      context: ./storrit
      dockerfile: Dockerfile
    env_file:
      - .env
    #environment:
      #SUBREDDIT:
      #RMQ_HOST:
      #REDIS_HOST: